version: '3'
services:
  myapp:
    image: exist/efs-backend-repo-default:1.0
    ports:
    - 9081:8081
    links:
    - mongodb
    depends_on:
    - mongodb
    container_name: efs-backend-repo-standalone
  mongodb:
    image: mongo:latest
    container_name: efs-backend-repo-standalone-mongodb
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/log
    volumes:
    - mongodata:/data/db
    - ./log:/log
    ports:
    - 27017:27017
    command: mongod --smallfiles
volumes:
  mongodata:
